repos:
  - repo: local
    hooks:
      - id: my-check
        name: "Custom Python Check"
        entry: python easy/backup.py
        language: system
        stages: [pre-commit, post-checkout]


#pip install pre-commit          # 한 번만
#pre-commit install              # .git/hooks/ 에 래퍼 스크립트 생성
#pre-commit run --all-files      # 수동 실행(첫 세팅 확인용)